name = "balancechain-node"
main = "src/index.js"
compatibility_date = "2025-08-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "balancechain_node"
database_id = "REPLACE_WITH_YOUR_D1_ID"

[vars]
CHAIN_ID = "balancechain-main"
# TODO: set your real genesis UTC (milliseconds since epoch)
GENESIS_UTC_MS = "1736565605"
MAX_FUTURE_SKEW_MS = "120000"
MAX_BATCH = "500"
INITIAL_UNLOCKED = "1200"
YEARLY_CAP = "120000"
